
OPERATORS = ["<", ">", "==", "!=", "(", ")"]

GOOGLE_FINANCE_URL = "https://www.google.com/finance"

tickers = {}

START_POSITION_X = 100
START_POSITION_Y = 100

RELX_MIN_INSERT = 0.375
RELX_MAX_INSERT = 0.755
RELY_INCR_INSERT = 0.10
RELY_BEGIN = 0.1
RELY_INCR_TEMPLATE = 0.13
RELX_MIN_TEMPLATE = 0.2
RELX_MAX_TEMPLATE = 0.45
CORNER_ROUND = 10